                                                                        services:
                                                                          # БД для сервиса управления заметками
                                                                          db_notes:
                                                                            # Название контейнера
                                                                            container_name: db_notes
                                                                            # Значения переменных окружения
                                                                            environment:
                                                                              MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
                                                                              MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
                                                                            # Образ для контейнера который будет скачан из DockerHub
                                                                            image: mongo
                                                                            # Меняем порт MongoDB в контейнере
                                                                            command: mongod --port ${MONGO_INITDB_PORT}
                                                                        
                                                                            # Настройки хранилища данных, необходим для сохранения
                                                                            # данных в базе данных при остановке контейнера
                                                                            volumes:
                                                                              - db_notes_vol:/data/db
                                                                            # Объявляем внутренную сеть докера, для
                                                                            # передачи данных между контейнерами
                                                                            networks:
                                                                              - server_net
                                                                          redis_notes:
                                                                            container_name: redis_notes
                                                                            image: redis
                                                                            command: --port ${REDIS_PORT}
                                                                        
                                                                            volumes:
                                                                              - redis_data:/data
                                                                            networks:
                                                                              - server_net
                                                                          db_auth:
                                                                            container_name: db_auth
                                                                            environment:
                                                                              POSTGRES_USER: ${POSTGRES_USER}
                                                                              POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                                                                              POSTGRES_DB: ${POSTGRES_DB}
                                                                            image: postgres:15-alpine
                                                                            ports:
                                                                              - ${POSTGRES_PORT}:${POSTGRES_PORT}
                                                                            command:
                                                                              - postgres
                                                                              - -c
                                                                              - port=${POSTGRES_PORT}
                                                                            volumes:
                                                                              - db_auth_vol:/var/lib/postgresql/data
                                                                            restart: always
                                                                            networks:
                                                                              - server_net
                                                                        
                                                                          # Cервис для управления пользователем
                                                                          auth:
                                                                            # Название контейнера
                                                                            container_name: auth
                                                                            # Папка контейнера для сборки
                                                                            build: ./auth
                                                                            # Указывает, что контейнер должен ждать запуск контейнеров
                                                                            # Так как необходимо, чтобы MongoDB и Redis были запущены
                                                                            depends_on:
                                                                              - db_auth
                                                                            # Объявляем внутренную сеть докера, для
                                                                            # передачи данных между контейнерами
                                                                            networks:
                                                                              - server_net
                                                                            # Порты, которые будут использоваться в контейнере
                                                                        
                                                                            # Внешние переменные окружения
                                                                            environment:
                                                                              # Порт который будет использоваться в контейнере
                                                                              AUTH_PORT: ${AUTH_PORT}
                                                                              # Секретный ключ для аутентификации
                                                                              JWT_SECRET: ${JWT_SECRET}
                                                                              # Настройки MongoDB, укзаваем в контейнере
                                                                              POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                                                                              POSTGRES_USER: ${POSTGRES_USER}
                                                                              POSTGRES_PORT: ${POSTGRES_PORT}
                                                                              POSTGRES_DB: ${POSTGRES_DB}
                                                                              POSTGRES_HOST: ${POSTGRES_HOST}
                                                                              POSTGRES_USE_SSL: ${POSTGRES_USE_SSL}
                                                                          notes:
                                                                            container_name: notes
                                                                            build: ./notes
                                                                            depends_on:
                                                                              - db_notes
                                                                              - redis_notes
                                                                            networks:
                                                                              - server_net
                                                                            environment:
                                                                              JWT_SECRET: ${JWT_SECRET}
                                                                              NOTES_PORT: ${NOTES_PORT}
                                                                              # /// mongo_db
                                                                              # Пользователь БД
                                                                              MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
                                                                              # Пароль БД
                                                                              MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
                                                                              # Порт который использует база данных
                                                                              MONGO_INITDB_PORT: ${MONGO_INITDB_PORT}
                                                                              # Хост базы данных,
                                                                              MONGO_INITDB_HOST: ${MONGO_INITDB_HOST}
                                                                              # /// redis
                                                                              # Порт Redis
                                                                              REDIS_PORT: ${REDIS_PORT}
                                                                              # Хост в сети докер
                                                                              REDIS_HOST: ${REDIS_HOST}
                                                                        
                                                                        
                                                                        # Конфигурация для хранилища данных
                                                                        volumes:
                                                                          db_notes_vol: {}
                                                                          redis_data: {}
                                                                          db_auth_vol: {}
                                                                        # Настройки сетей
                                                                        networks:
                                                                          server_net:
                                                                            driver: bridge
